#
# Makefile for the Mali drm device driver.  This driver provides support for the
# Direct Rendering Infrastructure (DRI) in XFree86 4.1.0 and higher.

ccflags-y = -Iinclude/drm
mali_drm-y := mali_drv.o

obj-$(CONFIG_DRM_MALI)   += mali_drm.o


